#!/bin/bash

# Get the hostname
HOSTNAME=$(hostname)

# Get the path of the current repository
REPOS_PATH=$(git rev-parse --show-toplevel)

# Extract the repository name from the repository path
REPO_NAME=$(basename $REPOS_PATH)

# Construct the log file path
LOG_FILE="/tmp/${HOSTNAME}_${REPO_NAME}.log"

echo "Git hook logs are available at: $LOG_FILE"

# Log start of the hook execution
echo "$(date): Starting hook execution" | tee -a $LOG_FILE

# Get the latest commit hash to be pushed
LATEST_COMMIT=$(git rev-parse HEAD)

# Log the latest commit hash
echo "$(date): Latest commit hash to be pushed is $LATEST_COMMIT" | tee -a $LOG_FILE

# Capture parameters and environment variables to the log file
echo "---" | tee -a $LOG_FILE
echo "Parameters: $@" | tee -a $LOG_FILE
echo "---" | tee -a $LOG_FILE
echo "Environment:" | tee -a $LOG_FILE
env | tee -a $LOG_FILE
echo "---" | tee -a $LOG_FILE
echo "Set:" | tee -a $LOG_FILE
set | tee -a $LOG_FILE
echo "---" | tee -a $LOG_FILE

# Get the path of the current repository
REPOS_PATH=$(git rev-parse --show-toplevel)
echo "$(date): Repository path is $REPOS_PATH" | tee -a $LOG_FILE
echo "---" | tee -a $LOG_FILE

# Pull the latest Docker image
echo "$(date): Pulling Docker image" | tee -a $LOG_FILE
docker pull ghcr.io/oriolrius/readme2notion 2>&1 | tee -a $LOG_FILE

# Check if the Docker pull was successful
if [ $? -ne 0 ]; then
  echo "$(date): Docker pull failed" | tee -a $LOG_FILE
  exit 1
fi
echo "---" | tee -a $LOG_FILE

# Run the Docker container with the specified command
echo "$(date): Running Docker container" | tee -a $LOG_FILE
docker run --rm --network host -v ${REPOS_PATH}:/repos ghcr.io/oriolrius/readme2notion --commit ${LATEST_COMMIT} /repos/README.md 2>&1 | tee -a $LOG_FILE

# Check if the Docker run was successful
if [ $? -ne 0 ]; then
  echo "$(date): Docker run failed" | tee -a $LOG_FILE
  exit 1
fi
echo "---" | tee -a $LOG_FILE

# Log end of the hook execution
echo "$(date): Hook execution finished" | tee -a $LOG_FILE
